"""
FastAPI version of the RAG app (alternative to Streamlit).

Notice: this file does NOT touch the RAG logic at all. It just imports
`ask()` from rag_chat.py and exposes it over a web API + simple HTML page.
This is good practice — keep your core logic separate from your UI/interface layer.

Run with: uvicorn main:app --reload
Then open: http://127.0.0.1:8000 in your browser
API docs (auto-generated by FastAPI) at: http://127.0.0.1:8000/docs
"""

from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from rag_chat import ask

app = FastAPI(title="RAG Document Assistant API")


class Question(BaseModel):
    question: str


@app.get("/", response_class=HTMLResponse)
def home():
    """Serves a simple HTML page with a question box (this replaces the Streamlit UI)."""
    return HTML_PAGE


@app.post("/ask")
def ask_question(payload: Question):
    """
    The actual API endpoint. Takes a JSON body like {"question": "..."}
    and returns {"answer": "...", "sources": [...]}.
    You can call this directly from curl, Postman, or any frontend (not just the HTML page below).
    """
    answer, sources = ask(payload.question)
    return {"answer": answer, "sources": sources}


HTML_PAGE = """
<!DOCTYPE html>
<html>
<head>
    <title>RAG Document Assistant</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 700px; margin: 50px auto; padding: 0 20px; }
        h1 { color: #333; }
        input[type=text] { width: 100%; padding: 10px; font-size: 16px; box-sizing: border-box; }
        button { padding: 10px 20px; font-size: 16px; margin-top: 10px; cursor: pointer; }
        #answer { margin-top: 20px; padding: 15px; background: #f4f4f4; border-radius: 8px; white-space: pre-wrap; }
        #sources { margin-top: 10px; font-size: 14px; color: #555; }
        #loading { display: none; color: #888; margin-top: 10px; }
    </style>
</head>
<body>
    <h1>RAG Document Assistant</h1>
    <p>Ask questions about the documents in your <code>data/</code> folder.</p>

    <input type="text" id="question" placeholder="Type your question here...">
    <button onclick="askQuestion()">Get Answer</button>

    <div id="loading">Searching documents and generating answer...</div>
    <div id="answer"></div>
    <div id="sources"></div>

    <script>
        async function askQuestion() {
            const question = document.getElementById("question").value;
            if (!question) return;

            document.getElementById("loading").style.display = "block";
            document.getElementById("answer").innerText = "";
            document.getElementById("sources").innerText = "";

            try {
                const response = await fetch("/ask", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ question: question })
                });
                const data = await response.json();

                document.getElementById("answer").innerText = "Answer: " + data.answer;
                document.getElementById("sources").innerText = "Sources: " + data.sources.join(", ");
            } catch (err) {
                document.getElementById("answer").innerText = "Error: " + err;
            } finally {
                document.getElementById("loading").style.display = "none";
            }
        }
    </script>
</body>
</html>
"""
